export const ADMIN_NAV = [
  { href: "/admin", label: "Dashboard" },
  { href: "/admin/identity", label: "Identity" },
  { href: "/admin/now", label: "Now" },
  { href: "/admin/record", label: "Record" },
  { href: "/admin/proofs", label: "Proofs" },
  { href: "/admin/places", label: "Places" },
  { href: "/admin/ventures", label: "Ventures" },
  { href: "/admin/ledger", label: "Commitments" },
  { href: "/admin/thinking", label: "Thinking" },
  { href: "/admin/signals", label: "Signals" },
  { href: "/admin/challenges", label: "Challenges" },
  { href: "/admin/ask", label: "Ask sources" },
  { href: "/admin/connect", label: "Contact requests" },
  { href: "/admin/media", label: "Media" },
  { href: "/admin/learning", label: "Learning" },
  { href: "/admin/security", label: "Security" },
  { href: "/admin/analytics", label: "Analytics" },
] as const;
